
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: warning
  logs:
    custom_components.stall.binary_sensor: debug

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


binary_sensor:
  - platform: stall
    name: Sun (Stall)
    entities:
      - sun.sun
    threshold: 1

  - platform: stall
    name: Weather (Stall)
    entities:
      - weather.home
    threshold: 2

  - platform: stall
    name: Both (Stall)
    entities:
      - sun.sun
      - weather.home
    threshold: 1